<div class="slider-seption">
    <div class="heading-title text-center">
        <h2 class="heading-title__title">AWESOME MAGENTO 2 STORES<br>CREATED WITH PEARL.</h2>
        <p class="subtitle-slide-1">At WeltPixel we turn complicated business requirements into simple solutions. Built on years of experience working with retail teams of all sizes, extensive</p>
        <p class="subtitle-slide-2">user testing, and a commitment to constant refinement,<b>our platform makes running your site easy so you can focus on running your business.</b></p>
    </div>
    <section class="regular slider">
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/5/_/5_1.jpg" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/4/_/4_1.jpg" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/b/o/bombus_-_original_610_x_449_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/j/o/johnson_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/t/h/the-fresh-company_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/b/e/bella-baby_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/s/c/schlafgut_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/r/o/robert-old_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/b/a/balleh_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/r/e/renaissance-skincare_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/s/i/silkn_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/c/a/canvas_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/s/u/sutils_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/p/h/pharmaca_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/s/i/sites-using-pearl-pure-rugs_1.jpg" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/2/_/2_1.jpg" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/c/a/carousel_1_1.png" />
        </div>
        <div>
            <img src="https://www.weltpixel.com/media/weltpixel/owlcarouselslider/images/m/a/main-image_2.png" />
        </div>

    </section>
</div>
