<fieldset  class="display-media">
    <div class="list">
        <div class="first-column">
        <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/docs.svg" class="list__img"> -->
            <h3 class="nav__link"><?=__("Configurations")?></h3>
            <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
        </span>        </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                    <div class="content-text-button">
                        <div class="text-button-click">
                            <span class="span-text"><?=__("Configurable products allow customers to choose options (Ex: shirt color). You need to create a simple product for each configuration (Ex: a product for each color).")?></span>
                            <button class="button-configurations"><?=__("Create Configuartions")?></button>
                        </div>
                    </div>
                </div>
            </li>

        </ul>

</div>
        </div>
    </div>
</fieldset>



 