<fieldset  class="display-media">
    <div class="list">
        <div class="first-column">
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
                        
                <h3 class="nav__link"><?=__("Customizable Options")?></h3>
            
            <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
        </span>        </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                    <div class="content-text-button">
                        <div class="text-button-click">
                            <span><?=__("Custom options let customers choose the product variations they want.")?></span>
                            <button class="button-configurations"><?=__("")?>Add Up-Sell Products</button>
                        </div>
                    </div>
                </div>
                
            </li>
        </ul>

    </div>
        </div>
    </div>
</fieldset>

