<fieldset  class="display-media">
    <div class="list">
        <div class="first-column">
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
                       
                <h3 class="nav__link"><?=__("")?>Design </h3>
          
            <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
        </span>        </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                <div class="input-Tax">
         <label for=""><?=__("Layaout")?></label>
        <div class="select-collapsible">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Layaout Updates ")?></item>
                                
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Empty")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("1 Colomn")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("2 Columns With left bar")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("2 columns with rightbar")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("3 Column")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Page -- Full width")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Category -- full width")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Category -- full width")?></item>
                            </option>
                           
                        </options>
                    </settings>
        </select>

        </div>
        </div>
        <div class="input-Tax">
        <label for=""><?=__(" Display Product Options In")?></label>
        <div class="select-collapsible">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("Product Info Column")?></item>
                                
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Block After Info Column")?></item>
                            </option>
                           
                        </options>
                    </settings>
        </select>

        </div>
        </div>
        <div class="input-Tax">
        <label for=""><?=__(" Custom Layout Update")?></label>
        <div class="select-collapsible">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
        </div>
   
                </div>
                
            </li>
        </ul>

    </div>
        </div>
    </div>
</fieldset>

