
<fieldset class="display-media">

    <div class="list">
        <div class="first-column">
        <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
                      
                <h3 class="nav__link"><?=__("Related Products, Up-Sells, and Cross-Sells")?> </h3>
            
            <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
        </span>        </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper topp">
                    <span class="relatic-span"><?=__("Related Products")?></span>
                    <div class="content-text-button">
                        <div class="text-button-click">
                            <span class="span-text"><?=__("An up-sell item is offered to the customer as a pricier or higher-quality alternative to the product the customer is looking at.")?></span>
                            <button class="button-configurations"><?=__("Add Related Products")?></button>
                        </div>
                    </div>
                </div>

                <div class="fieldset-wrapper">
                    <span class="relatic-span"><?=__("Up-Sell Products")?></span>
                    <div class="content-text-button">
                        <div class="text-button-click">
                            <span class="span-text"><?=__("An up-sell item is offered to the customer as a pricier or higher-quality alternative to the product the customer is looking at.")?></span>
                            <button class="button-configurations"><?=__("Add Up-Sell Products")?></button>
                        </div>
                    </div>
                </div>

                <div class="fieldset-wrapper">
                    <span class="relatic-span"><?=__("Cross-Sell Products")?></span>
                    <div class="content-text-button">
                        <div class="text-button-click">
                            <span class="span-text"><?=__("An up-sell item is offered to the customer as a pricier or higher-quality alternative to the product the customer is looking at.")?></span>
                            <button class="button-configurations"><?=__("Add Cross-Sell Products")?></button>
                        </div>
                    </div>
                </div>
            </li>
        </ul>

    </div>


        </div>
    </div>


  
</fieldset>

