<fieldset  class="display-media">
    <div class="list">
        <div class="first-column">
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            
                <h3 class="nav__link"><?=__("Shedule Desing Update")?> </h3>

            <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
        </span>        </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">

                <div class="input-text">
        <label for=""><?=__(" Schedule Update From")?></label>
        <input name="price" type="date" class="input-date-form " id="vendor-product-form-price" >
        <input name="price" type="date"  class="input-date-form " id="vendor-product-form-price" >

        </div>
                <div class="input-Tax">
         <label for=""><?=__(" New Theme")?></label>
        <div class="select-collapsible">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("--Please Select--")?></item>
                                
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Ag software")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Magento Blank")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Magento Luma")?></item>
                            </option>
                            
                           
                           
                        </options>
                    </settings>
        </select>

        </div>
        </div>
        <div class="input-Tax">
        <label for=""><?=__("  New Layout")?></label>
        <div class="select-collapsible">
        <select  class="select-tax" name="" id=""> 
        <settings>
        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Layaout Updates ")?></item>
                                
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Empty")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("1 Colomn")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("2 Columns With left bar")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("2 columns with rightbar")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("3 Column")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Page -- Full width")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Category -- full width")?></item>
                            </option>
                            <option name="2" xsi:type="array">
                                <item name="label" xsi:type="string"><?=__("Category -- full width")?></item>
                            </option>
                           
                        </options>
                    </settings>
        </select>

        </div>
        </div>
    
   
                </div>
                
            </li>
        </ul>

    </div>
        </div>
    </div>
</fieldset>

