<fieldset  class="display-media">
    <div class="list">
        <div class="first-column">
<div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
                        
                <h3 class="nav__link"><?=__("Product in Websites")?> </h3>
            
            <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
        </span>        
        </div>

        <ul class="list__show">
            <li class="list__inside">
            <div class="fieldset-wrapper websites-wraperr">
                
            <label for="websites-input" class="websites-text">
                <input type="checkbox" id="websites-input">
                <span > <?=__("Websites")?> </span>

            </label>
            
            </div>
               
                
            </li>
        </ul>

    </div>


        </div>
    </div>
</fieldset>
