<div id="loader" data-role="loader" class="loading-mask main-loader">

    <!--PARA TENER UN LOADER UTILIZANDO ALGUN GIF DESCOMENTA EL SIGUIENTE CODIGO.-->
    <div class="loader-image">
        <img src="https://www.weltpixel.com/static/version1679594893/frontend/Pearl/weltpixel_custom/en_US/images/loader-1.gif" alt="Loading...">
    </div>


    <!--PARA TENER UN LOADER UTILIZANDO ALGUN TEXTO DESCOMENTA EL SIGUIENTE CODIGO.-->
   <!--<div class="loader-text">
        <?php /*echo __('Cargando...') */?>
    </div>-->

    <!--PARA TENER UN LOADER UTILIZANDO ALGUNA ANIMACION DESCOMENTA EL SIGUIENTE CODIGO.-->
    <!--<div class="loader-animation">
        <div></div>
        <div></div>
        <div></div>
    </div>-->

</div>

<script>
    require(['jquery', 'loader'], function ($) {
        'use strict';

        $('#loader').loader({
            icon: 'AgSoftware_Loader/images/loader.gif'
        });
    });
</script>
