<div id="one-minute-installation" class="section-wrapper center-text gray-bg row-container padding-bottom-double">
    <div class="col-xs-12 col-md-10 col-md-push-1 padding-bottom">
        <div class="heading-title center padding-bottom">
            <h2>LET'S CHECK IT OUT.</h2>
        </div>
        <div class="feature-box center media-box fbox-bg vimeo-vid vimeo-box-shaddow">
            <div class="fbox-media">
                <div style="padding:56% 0 0 0;">
                    <iframe src="https://player.vimeo.com/video/366452359?title=0&amp;byline=0&amp;portrait=0&amp;loop=1" style="position:absolute;top:0;left:0;width:100%;height:100%;" frameborder="0" allow="autoplay; fullscreen" allowfullscreen=""></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section-wrapper">
    <div class="section-wrapper__title">
        <h2>LET'S CHECK IT OUT.</h2>
    </div>
    <div class="section-wrapper__video">
        {{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="9"}}
    </div>
</div>