<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) : ?>
    <a href="<?= $block->escapeUrl($block->getPrintUrl()) ?>" class="action print" target="_blank" rel="noopener">
        <?= $block->escapeHtml(__('Print receipt')) ?>
    </a>
    <?= $block->getChildHtml() ?>
    <div>
        <img class="thanks-imagen" alt="<?= __("AgSoftware Logo") ?>" src="<?= $block->getViewFileUrl('images/thanks.png')?>">
    </div>
<?php endif; ?>