<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="foother">
        <div class="contenedor-espacio">

            <div class="contenedor-espacio1">
                <div class="colunna1 one">
                    <p>
                        <a class="a-numero1" href="/"  aria-label="AgSoftware">
                            <img class="imagen-logo"
                                alt="<?=__("AgSoftware Logo")?>"
                                src="<?=$block->getBaseUrl().'media/logo/stores/1/option-3-1.png'?>">
                        </a>
                    </p>

                    <div class="tres">
                        <a class="a-numerom" href=""><?=__("agsoftware.online@gmail.com")?></a>

                        <a class="a-numerom" href="#address"><?=__("Colombia: Cra 7A # 8 - 39, Guachené, Cauca")?></a>

                        <a class="a-numerom" href="https://wa.link/hrj33w"><?=__("+57 320 777 5771")?></a>
                    </div>

                    <p>
                        <?php /*
                        <a href="" target="_blank" rel="noopener">
                            <img data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-adobe-innovate.png"
                                alt="Adobe Innovate Exchange Partner" class="img-two imge"
                                src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-adobe-innovate.png">
                        </a>
                        */?>
                    </p>


                    <p class="mismas">
                    <?php /*
                        <img class="img-misma"
                            data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-developer.png"
                            alt="badge-cert-developer"
                            src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-developer.png">
                        <img class="img-misma"
                            data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-dev-plus.png"
                            alt="badge-cert-dev-plus"
                            src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-dev-plus.png">
                        <img class="img-misma"
                            data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-frontend.png"
                            alt="badge-cert-frontend"
                            src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-frontend.png">
                        */?>
                    </p>

                    <p >
                        <a href="" target="_blank" rel="noopener">
                        <?php /*
                            <img class="footer-img lazyload"
                                data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-trustpilot.png"
                                alt="mageplaza trustpilot"
                                src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-trustpilot.png">
                        */?>
                        </a>
                    </p>
                </div>

                <div class="colunna2  one">
                    <h4 class="h4-texto">
                        <?php
                            echo __("Company")
                        ?>    
                    </h4>

                    <ul class="listas">
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow">
                                <?php
                                    echo __("About us")
                                ?>        
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href=""
                                rel="nofollow">
                                <?php
                                    echo __("Customer Says")
                                ?>  
                            </a>
                            </li>
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow">
                                <?php
                                    echo __("Discount Programs")
                                ?>   
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow"> 
                                <?php
                                    echo __("Privacy &amp; Policy")
                                ?>   
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow">
                                <?php
                                    echo __("Terms &amp; Conditions")
                                ?>    
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow">
                                <?php
                                    echo __("License Agreement")
                                ?>   
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href=""
                                rel="nofollow">
                                <?php
                                    echo __("Become a Contributor")
                                ?>  
                            </a>
                        </li>
                    </ul>

                </div>

                <div class="colunna2  one">
                    <h4 class="h4-texto li-2 cu-services">
                        <?php
                            echo __("Customer Services")
                        ?>
                    </h4>
                    <ul class="listas  li-2">
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow">
                                <?php
                                    echo __("Support")
                                ?>
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href=""
                                rel="nofollow">
                                <?php
                                    echo __("Schedule a call")
                                ?>
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href=""
                                rel="noopener nofollow">
                                <?php
                                    echo __("Reward Program")
                                ?>
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href=""
                                rel="nofollow">
                                <?php
                                    echo __("Partner Program")
                                ?>
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href="" target="_blank"
                                rel="nofollow">
                                <?php
                                    echo __("Deals")
                                ?>
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href=""
                                rel="noopener nofollow">
                                <?php
                                    echo __("Affiliate Program")
                                ?>
                            </a>
                        </li>
                        <li>
                            <a class="a-numerom2" href="" rel="nofollow">
                                <?php
                                    echo __("Official Partners")
                                ?>
                            </a>
                        </li>
                    </ul>


                </div>

                <div class="block newsletter rojo">
                    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
                    <div class="content conten_subscribe">
                    <h3 class="tex-subs">
                        <?php
                            echo __("Subscribe")
                        ?>      
                    </h3>
                        <form class="form subscribe"
                            novalidate
                            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                            method="post"
                            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                            id="newsletter-validate-detail">
                            <div class="field newsletter">
                                <div class="control">
                                    <label for="newsletter">
                                        <span class="label">
                                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                                        </span>
                                        <input name="email" type="email" id="newsletter"
                                            placeholder="<?= $block->escapeHtml(__(' your email ')) ?>"
                                            data-mage-init='{"mage/trim-input":{}}'
                                            data-validate="{required:true, 'validate-email':true}"
                                        />
                                    </label>
                                </div>
                            </div>
                            <div class="actions">
                                <button class="action subscribe primary icon-subscribe"
                                        title="<?= $block->escapeHtmlAttr(__('')) ?>"
                                        type="submit"
                                        aria-label="&#xF6C0">
                                    <span class="" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
                                    <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z"/>
                                    </svg><?= $block->escapeHtml(__('')) ?></span>
                                </button>
                            </div>
                        </form>
                            <h4 class="titulo-lista">
                                <?php
                                    echo __("Stay in touch")
                                ?>   
                            </h4>
                        <div class="redes-sociales">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                                </svg>

                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                                </svg>


                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
                                <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
                                </svg>


                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                                </svg>

                                </div>



                    </div>
                </div>

            </div>

            <div class="contenedor-dos">
                <div class="corto">
                    <p class="dentro">
                        <?php
                            echo __("© Copyright 2022 by AgSoftware. All Rights Reserved.")
                        ?>
                    </p>
                    <p class="dentro">
                        <?php
                            echo __("Magento® Commerce or Adobe Commerce is a registered trademark by Adobe.")
                        ?>    
                    </p>
                </div>

                <div class="largo">
                    <a class="dentro" href=""
                        title="Magento 2 one step checkout">
                        <?php
                            echo __("One Step Checkout")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Layered Navigation Ultimate">
                        <?php
                            echo __("Layered Navigation")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Affiliate extension">
                        <?php
                            echo __("Affiliate PRO")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 SEO extension">
                        <?php
                            echo __("Magento 2 SEO")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 SMS Notification">
                        <?php
                            echo __("SMS Notification")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 blog extension">
                        <?php
                            echo __("Better Blog")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href="">
                        <?php
                            echo __("Security Suite")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Gift Card, Certificates">
                        <?php
                            echo __("Gift Card")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Reward Points">
                        <?php
                            echo __("Reward Points")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Shop by brand">
                        <?php
                            echo __("Shop by Brand")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href="">
                        <?php
                            echo __("SMTP")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href="">
                        <?php
                            echo __("PDF Invoice")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href="" title="Avada Commerce">
                        <?php
                            echo __("AVADA")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 SMS, Email Marketing">
                        <?php
                            echo __("Email Marketing")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href="" title="Shopware docs">
                        <?php
                            echo __("Shopware")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href="" title="Mageplaza Sitemap">
                        <?php
                            echo __("Sitemap")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Administration extensions">
                        <?php
                            echo __("Administration extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Checkout extensions">
                        <?php
                            echo __("Checkout extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Promotions extensions">
                        <?php
                            echo __("Promotion extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 B2B extensions">
                        <?php
                            echo __("B2B extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Navigation extensions">
                        <?php
                            echo __("Navigation extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Product Enchancements extensions">
                        <?php
                            echo __("Product Enchancements")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Sales Motivation extensions">
                        <?php
                            echo __("Sales Motivation")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Content Management extensions">
                        <?php
                            echo __("Content Management")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 User Experience extensions">
                        <?php
                            echo __("User Experience")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Order Management extensions">
                        <?php
                            echo __("Order Management")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 SEO Suite extensions">
                        <?php
                            echo __("SEO Suite")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Payment extensions">
                        <?php
                            echo __("Payment extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Shipping &amp; Fee extensions">
                        <?php
                            echo __("Shipping &amp; Fee")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 CRO Extensions">
                        <?php
                            echo __("CRO Extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Security extensions">
                        <?php
                            echo __("Security extensions")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Shopify trial">
                        <?php
                            echo __("Shopify Trial")
                        ?>      
                    </a>
                     /
                    <a class="dentro" href=""
                        title="Magento 2 Migration">
                        <?php
                            echo __("Migrate Magento 1 to Magento 2")
                        ?>      
                    </a>
                </div>
            </div>

        </div>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
