

<div class="display-media">
        
        <div class="list ">

           
<div class="first-column">
    <div class="list__item list__item--click">
        <div class="list__button list__button--click list-settings">
            <!-- <img src="assets/docs.svg" class="list__img"> -->
        <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
           <h3 class="nav__link"><?=__("Mercado Pago")?></h3>

        </div>                   
     </div>

        <ul class="list__show">
            <div class="list__inside">
                <div class="fieldset-wrapper">
                <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/docs.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Credentials")?></h3>

        </div>    
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                    
                </div>
            </li>

        </ul>

    </div>

    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Order Management")?></h3>

        </div>            
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper topp">
                    
                </div>

               
               
            </li>
        </ul>

    </div>

    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Checkout - Credit and Debit Card")?></h3>

        </div>        
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                    
                </div>
                
            </li>
        </ul>

    </div>
   
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Checkout - Offline Pymements Methods(Ticked)")?></h3>

        </div>           
    </div>

        <ul class="list__show">
            <li class="list__inside">
            <div class="fieldset-wrapper websites-wraperr">
                
            
            </div>
               
                
            </li>
        </ul>

    </div>
   
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Pro")?></h3>

        </div>          
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                
                </div>
                
            </li>
        </ul>

    </div>
   
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Checkout - Bank Transfer")?></h3>

        </div>         
     </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">

             
    
   
                </div>
                
            </li>
        </ul>

    </div>

    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
            <!-- <img src="assets/bell.svg" class="list__img"> -->
            <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Advanced")?></h3>

        </div>    
        </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper websites-wraperr" websites-wraperr>
          
                </div>
                
            </li>
        </ul>

    </div>
   
    
                </div>
            </div>
          
        <div>
 
</div>

        </ul>
    </div>

  

   
   
   
</div>


            

        </div>
    
</div>
