<fieldset class=display-settings>
  <div class="display-media">
<div class="container-user-guide">

    <div class="container-items" data-mage-init='{
            "collapsible":{
                "collapsible": true,
                "openedState": "opened",
                "active": false,
                "animate":{ "duration" :300, "easing":"easeOutCubic"}
            }}'>

        <div class="container-row" data-role="title">
            
        <span class="column-2-arrow"><i class="fa-solid fa-chevron-down arrow-v"></i> 
        </span>
        
            <div class="column-1">
               <span class ="title-mercado-list"><?=__("Mercado Pago")?></span>
            </div>

            

        </div>

        <div class="container-demo-content" data-role="content">
                <div class="container-links">
                <div class="display-config-media">
        
        <div class="list ">

           
<div class="first-column">
    <div class="list__item list__item--click ">
        <div class="list__button list__button--click">
        <div class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </div>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Credentials")?></h3>

        </div>       
    </div>

        <ul class="list__show">
            <div class="list__inside">
                <fclose class="fieldset-wrapper">
                <div class="input-text credential">
                    <label for="vendor-product-form-name " class="relative-content"><?=__("Public key")?></label>
                    <input name="name" class="input-text first-four" id="vendor-product-form-name" value="">
                    
                </div>

                <div class="input-text credential">
                    <label for="vendor-product-form-name " class="relative-content"><?=__("Access Token")?></label>
                    <input name="name" class="input-text first-four" id="vendor-product-form-name" value="">
                </div>
                
                <span class="span-key-tex">
                    <span><?=__("Get your credential access_token and public_key, visit the country in which  your account was created: Argentina, Brazil, Chile, Colombia, Mexico, Uruguay and Peru")?></span>
                </span>

                
                </fclose>
                
            </div>
          
        <div>
 
</div>

        </ul>
    </div>

    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
        <epa class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </epa>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Order Management")?></h3>

        </div>           
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                <div class="input-managent input-Tax">
        <label for=""><?=__("Order status when paymen is approved")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is in_process")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is pending")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__("  Order status when paymen is rejected")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is canceled")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is chargeback")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  

    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is in_mediation")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is refunded")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Order status when paymen is patally")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div> 
    <div class="integration">
    <span>API integration</span>
    </div>
 
    <div class="input-managent input-Tax">
        <label for=""><?=__(" Refund payment")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
    <div class="input-managent ">
        <label for=""><?=__(" cancel payment")?></label>
        <div class="select-managent">
        <select  class="select-tax" name="" id=""> 
        <settings>
                        <options>
                            <option name="1" xsi:type="array">
                                <item name="value" xsi:type="string"><?=__("No Update")?></item>
                                
                            </option>
                            
                           
                        </options>
                    </settings>
        </select>

        </div>
    </div>  
                </div>
            </li>

        </ul>

    </div>

    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
        <epa class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </epa>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Checkout - Credit and Debit Card ")?></h3>

        </div>     
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper topp">
                   
                </div>

                <div class="fieldset-wrapper">
                   
                </div>

             
            </li>
        </ul>

    </div>

    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
        <epa class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </epa>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Checkout - Offline Payments Methods (Ticket)")?></h3>

        </div>             
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
                    
                </div>
                
            </li>
        </ul>

    </div>
   
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
        <epa class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </epa>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("checkout Pro")?></h3>

        </div>          
    </div>

        <ul class="list__show">
            <li class="list__inside">
            <div class="fieldset-wrapper websites-wraperr">
                
          
            
            </div>
               
                
            </li>
        </ul>

    </div>
   
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
        <epa class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </epa>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("Custom Checkout - Bank Transfer")?></h3>

        </div>          
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">
          
   
                </div>
                
            </li>
        </ul>

    </div>
   
    <div class="list__item list__item--click">
        <div class="list__button list__button--click">
        <epa class="content-settings-arrow">
           <span  class="list__arrow">
            <i class="fa-solid fa-chevron-down arrow-v"></i>        
            </span>
        </epa>
        <div class="title-settings">
            <h3 class="nav__link"><?=__("advanced")?></h3>

        </div>        
    </div>

        <ul class="list__show">
            <li class="list__inside">
                <div class="fieldset-wrapper">

    
   
                </div>
                
            </li>
        </ul>

    </div>

    
   
    

   
   
   
</div>


            

        </div>
    
</div>

    
                </div>
        </div>

    </div>
</div>
</fieldset>


