<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 * @var $_helperCustomer \AgSoftware\Vendor\Helper\Data
 */
?>
<?php
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
$_helperCustomer = $this->helper(\AgSoftware\Vendor\Helper\Data::class);
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <tbody>
            <?php foreach ($_additional as $_data) :?>
                    <tr>
                        <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                        <?php if($_data['code'] === 'agsoftware_vendor_id'):?>
                            <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label'])?>">
                                <?= /* @noEscape */ $_helperCustomer->getCustomerName($_data['value'])?></td>
                        <?php else:?>
                            <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                        <?php endif;?>
                    </tr>

            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
