<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">

    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />

</div>
<div class="container-days-support">

    <div class="container-row-days">
        <div class="container-money-back">
            <div class="text-center">
                <img class="mt-1 img-peso"
                     src="<?= $this->getViewFileUrl('Magento_Catalog::images/money-back.svg')?>">
                <p class="text-center">
                    <?=__("60-day Money Back")?>
                </p>
            </div>
        </div>

        <div class="container-update">
            <div class="text-center">
                <img class="mt-1 img-arraw"
                     src="<?= $this->getViewFileUrl('Magento_Catalog::images/updates.svg')?>">
                <p class="text-center">
                    <?=__("Frequent Update")?>
                </p>
            </div>
        </div>

        <div class="container-suport">
            <div class="text-center">
                <img class="mt-1 img-reloj"
                     src="<?= $this->getViewFileUrl('Magento_Catalog::images/support.svg')?>">
                <p class="text-center">
                    <?=__("365-day Support")?>
                </p>
            </div>
        </div>

    </div>

</div>



<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
