<section class="account-social-login">
    <div class="social-login_title">
        <h3 class="title-login_with">
            <span class="sing-up sing-in">
                <?php
                    echo __("sing up sing in with")
                ?>
            </span> 
        </h3>
    </div>
    <div class="social-login_container">
        <div class="account-google login">
            <a class="login-google google">
                <?php
                    echo __("sing in with google")
                ?>
            </a>
        </div>
        <div class="account-facebook login">
            <a class="login-facebook facebook">
                <?php
                    echo __("sing in with facebook")
                ?>
            </a>
        </div>
    </div>
</section>