
  
  <footer class="foother">
        <div class="contenedor-espacio">

            <div class="contenedor-espacio1">
                <div class="colunna1 one">
                    <p>
                        <a class="a-numero1" href="/" aria-label="Mageplaza">
                            <img class="imagen1  img-two"
                                data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/logo-darkbg.png"
                                alt="Mageplaza logo white"
                                src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/logo-darkbg.png">
                        </a>
                    </p>

                    <div class="tres">
                        <a class="a-numerom" href="">support@mageplaza.com</a>

                        <a class="a-numerom" href="#address">USA: 100 Church St, Manhattan, New York</a>

                        <a class="a-numerom" href="#address-2">VN: 102 Tran Phu, Ha Dong, Hanoi</a>
                    </div>

                    <p>
                        <a href="" target="_blank" rel="noopener">
                            <img data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-adobe-innovate.png"
                                alt="Adobe Innovate Exchange Partner" class="img-two imge"
                                src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-adobe-innovate.png">
                        </a>
                    </p>


                    <p class="mismas">
                        <img class="img-misma"
                            data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-developer.png"
                            alt="badge-cert-developer"
                            src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-developer.png">
                        <img class="img-misma"
                            data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-dev-plus.png"
                            alt="badge-cert-dev-plus"
                            src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-dev-plus.png">
                        <img class="img-misma"
                            data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-frontend.png"
                            alt="badge-cert-frontend"
                            src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-cert-frontend.png">
                    </p>

                    <p >
                        <a href="" target="_blank" rel="noopener">
                            <img class="footer-img lazyload"
                                data-src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-trustpilot.png"
                                alt="mageplaza trustpilot"
                                src="https://www.mageplaza.com/skin/frontend/mageplaza/default/img/badge/badge-trustpilot.png">
                        </a>
                    </p>
                </div>

                <div class="colunna2  one">
                    <h4 class="h4-texto">Company</h4>

                    <ul class="listas">
                        <li><a class="a-numerom2" href="" rel="nofollow">About
                                us</a></li>
                        <li><a class="a-numerom2" href=""
                                rel="nofollow">Customer Says</a></li>
                        <li><a class="a-numerom2" href="" rel="nofollow">Discount
                                Programs</a></li>
                        <li><a class="a-numerom2" href="" rel="nofollow">Privacy
                                &amp; Policy</a></li>
                        <li><a class="a-numerom2" href="" rel="nofollow">Terms &amp;
                                Conditions</a></li>
                        <li><a class="a-numerom2" href="" rel="nofollow">License
                                Agreement</a></li>
                        <li><a class="a-numerom2" href=""
                                rel="nofollow">Become a Contributor</a></li>
                    </ul>

                </div>

                <div class="colunna2  one">
                    <h4 class="h4-texto li-2">Customer Services</h4>
                    <ul class="listas  li-2">
                        <li><a class="a-numerom2" href="" rel="nofollow">Support</a>
                        </li>

                        <li><a class="a-numerom2" href=""
                                rel="nofollow">Schedule a call</a></li>
                        <li><a class="a-numerom2" href=""
                                rel="noopener nofollow">Reward Program</a></li>
                        <li><a class="a-numerom2" href=""
                                rel="nofollow">Partner Program</a></li>
                        <li><a class="a-numerom2" href="" target="_blank"
                                rel="nofollow">Deals</a></li>
                        <li><a class="a-numerom2" href=""
                                rel="noopener nofollow">Affiliate Program</a></li>
                        <li><a class="a-numerom2" href="" rel="nofollow">Official
                                Partners</a></li>
                    </ul>

                   
                </div>
                <div class="rojo">
                  <h4 class="titulo-lista">Stay in touch</h4>

                
                </div>


            </div>

            <div class="contenedor-dos">
                <div class="corto">
                    <p class="dentro">© Copyright 2022 by Mageplaza. All Rights Reserved.</p>
                    <p class="dentro">Magento® Commerce or Adobe Commerce is a registered trademark by Adobe.</p>
                </div>

                <div class="largo">
                    <a class="dentro" href=""
                        title="Magento 2 one step checkout">One Step Checkout</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Layered Navigation Ultimate">Layered Navigation</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Affiliate extension">Affiliate PRO</a> /
                    <a class="dentro" href=""
                        title="Magento 2 SEO extension">Magento 2 SEO</a> /
                    <a class="dentro" href=""
                        title="Magento 2 SMS Notification">SMS Notification</a> /
                    <a class="dentro" href=""
                        title="Magento 2 blog extension">Better Blog</a> /
                    <a class="dentro" href="">Security Suite</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Gift Card, Certificates">Gift Card</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Reward Points">Reward Points</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Shop by brand">Shop by Brand</a> /
                    <a class="dentro" href="">SMTP</a> /
                    <a class="dentro" href="">PDF Invoice</a>
                    /
                    <a class="dentro" href="" title="Avada Commerce">AVADA</a> /
                    <a class="dentro" href=""
                        title="Magento 2 SMS, Email Marketing">Email Marketing</a> /
                    <a class="dentro" href="" title="Shopware docs">Shopware</a>
                    /
                    <a class="dentro" href="" title="Mageplaza Sitemap">Sitemap</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Administration extensions">Administration extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Checkout extensions">Checkout extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Promotions extensions">Promotion extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 B2B extensions">B2B extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Navigation extensions">Navigation extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Product Enchancements extensions">Product Enchancements</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Sales Motivation extensions">Sales Motivation</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Content Management extensions">Content Management</a> /
                    <a class="dentro" href=""
                        title="Magento 2 User Experience extensions">User Experience</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Order Management extensions">Order Management</a> /
                    <a class="dentro" href=""
                        title="Magento 2 SEO Suite extensions">SEO Suite</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Payment extensions">Payment extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Shipping &amp; Fee extensions">Shipping &amp; Fee</a> /
                    <a class="dentro" href=""
                        title="Magento 2 CRO Extensions">CRO Extensions</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Security extensions">Security extensions</a> /
                    <a class="dentro" href=""
                        title="Shopify trial">Shopify Trial</a> /
                    <a class="dentro" href=""
                        title="Magento 2 Migration">Migrate Magento 1 to Magento 2</a>
                </div>
            </div>




        </div>
    </footer>
  