<div class="panel-header">
    <ul class="header-links">
        <li class="greet-welcome">
            <?php
                echo __("welcome to megaplaza dashboard")
            ?>
        </li>
        <li class="link-contact">
            <a href="/contact">
                <?php
                echo __("contact us")
                ?>
            </a>
        </li>
        <li class="link-sing-in">
            <a href="https://trebol-store.test/customer/account/login/referer/aHR0cHM6Ly90cmVib2wtc3RvcmUudGVzdC8%2C/">
                <?php
                echo __("sign in")
                ?>
            </a>
        </li>
        <li class="link-create-account">
            <a href="https://trebol-store.test/customer/account/create/">
                <?php
                echo __("create an account")
                ?>
            </a>
        </li>
        <li class="link-image">
            <a href="https://trebol-store.test/customer/account/create/">
                <img src="https://dashboard.mageplaza.com/static/version1659059478/frontend/Smartwave/porto/en_US/Mageplaza_WhatsNew/media/icons/ic_explore_bell.png" alt="notificacion">
            </a>
        </li>
    </ul>
</div>