<?php
/**
 *@var \Magento\Catalog\Block\Product\View $block
 *@var \Magento\Catalog\Model\Product $product
 */
$product = $block->getProduct();
?>
<div class="container-chat-new">
    <div class="content-chat">
        <img class="icon-img" src="<?= $this->getViewFileUrl('Magento_Catalog::images/chat-now.svg')?>">
        <a class="text-chat" target="_blank" href="https://wa.me/<?=$product->getData('whatsapp')?>">
            <?php
                echo __("Chat now")
            ?>
        </a>
    </div>
</div>


<div class="avandc-container">
    <div class="avandc-section">
        <div class="future-container">
            <div class="future-banner">
                <h2 class="ftr-h2">
                    <span class="text-ftr">Llega demasiado pronto el futuro. </span>¿Avanzamos juntos?</h2>
                <div class="ftr-button">
                    <a href="" class="secon-button avd-button">¡Avancemos!</a>
                </div>
            </div>
        </div>
    </div><div class="fixed-background"></div></div>

<style>

    .pcin-fott{
        position: relative;
        top: 180px;
        color: var(--title-Color);
        z-index: 1;
        padding: 0px 3%;

    }

    .avandc-section {
        width: 100%;
        max-width: 1280px;
        margin-right: auto;
        margin-left: auto;
    }
    .future-container {
        display: flex;
        min-height: 280px;
        padding: 60px 70px;
        align-items: center;
        border-radius: 24px;
        background-color: #003a7f;
        background-image: url("https://uploads-ssl.webflow.com/5ff9f08ad0f45f13b2c0e743/5ff9f08a3928de842a400863_Pattern%20Shape.svg");
        background-position: 50% 50%;
        background-size: cover;
    }
    .future-banner {
        display: flex;
        width: 100%;
        justify-content: space-between;
        align-items: center;
    }
    .ftr-h2 {
        margin-top: 0px;
        margin-bottom: 0px;
        color: #fef7fd;
        font-family: var(--fontFamily);
        line-height: 1.3;
        font-weight: 500;
        letter-spacing: -0.03em;
        display: inline-grid;
    }
    .text-ftr {
        color: #01d2fc;
        font-size: 38px;
    }
    .ftr-button {
        display: flex;
        width: 50%;
        justify-content: flex-end;
    }
    .secon-button {
        background-color: #fef7fd;
        color: #6a35ff;
        position: relative;
        display: flex;
        min-height: 60px;
        padding-right: 40px;
        padding-left: 40px;
        justify-content: center;
        align-items: center;
        font-family: 'Montserrat', sans-serif;
        font-size: 16px;
        font-weight: 500;
        text-align: center;
    }


    .foother {
        padding-top: 210px;
    }
    .page-footer {
        margin-top: 0px;
    }





    @media screen and (max-width: 991px){
        .future-banner {
            flex-direction: column;
            justify-content: center;
            text-align: center;
        }
        .ftr-button {
            width: 100%;
            margin-top: 40px;
            justify-content: center;
        }
        .future-container {
            padding: 65px 25px;


        }
    }
    @media screen and (max-width: 768px){
        .pcin-fott {



        }
    }
    @media screen and (max-width: 767px){
        .future-container{
            padding-right: 40px;
            padding-left: 40px;
            margin-top: -144px;
        }
        .pcin-fott {

            top: 200px;

        }
        .page-footer {
            margin-top: -15px;
        }
    }

    @media screen and (max-width: 479px){
        .ftr-h2 {
            font-size: 38px;
        }
        .pcin-fott {
            top: 130px;
        }
        .page-footer {
            margin-top: -120px;
        }

    }


</style>
