<div class="cont-links-review">
    <ul class="cont-list-review">
        <li class="li-product-reviews">
            <a href="#">
                API/GraphQL is available for this Company Accounts extension by Mageplaza
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                Create company accounts
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                Multiple user account roles with permissions
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                Unlimited users
            </a>
        </li>
        <li class="li-product-reviews">
            <a>Automatic email notifications</a>
        </li>
    </ul>
</div>
