<div class="cont-links-review">
    <ul class="cont-list-review">
        <li class="li-product-reviews">
            <a href="#">
                <?php
                    echo __("API/GraphQL is available for this Company Accounts extension by Mageplaza")
                ?>    
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                <?php
                    echo __("Create company accounts")
                ?>
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                <?php
                    echo __("Multiple user account roles with permissions")
                ?>
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                <?php
                    echo __("Unlimited users")
                ?>
            </a>
        </li>
        <li class="li-product-reviews">
            <a>
                <?php
                    echo __("Automatic email notifications")
                ?>    
            </a>
        </li>
    </ul>
</div>
