<?php
/**
 *@var \Magento\Catalog\Block\Product\View $block
 *@var \Magento\Catalog\Model\Product $product
 */
$product = $block->getProduct();
if($product->getData('service')){
    return;
}
?>
<div class="container-user-guide" data-mage-init='{"accordion":{
                                    "openedState": "active",
                                    "collapsible": true,
                                    "active": false,
                                    "animate":{ "duration" :300, "easing":"easeOutCubic"},
                                    "multipleCollapsible": false}}'>

    <div class="container-items" data-role="collapsible">
        <div class="container-row" data-role="trigger">
            <div class="column-1">
                <img class="icon-img"
                     alt="<?=__("logo Demo")?>"
                     src="<?= $this->getViewFileUrl('Magento_Catalog::images/demo.svg')?>">
                <span><?=__("Demo")?></span>
            </div>
            <span class="column-2-arrow">➜</span>

        </div>

        <div class="container-demo-content" data-role="content">
                <div class="container-links">
                    <a class="links links-frontend"
                       target="_blank" href="<?=$product->getData('demo_pdf')?>">
                        <?=__("Document")?></a>
                    <a class="links links-backend"
                       target="_blank" href="<?=$product->getData('demo_video')?>">
                       <?=__("Video")?></a>
                </div>
                <div class="container-hosted">
                    <span class="hosted-in|fo"><?=__("This demo is hosted on")?></span>
                    <a class="hosted-links"
                       target="_blank" href="<?=$product->getData('demo_pdf')?>">
                        <?=__("Document")?></a>
                </div>
        </div>

    </div>


    <div class="container-guide-content" data-role="collapsible">

        <div class="container-row" data-role="trigger">
            <div class="column-1" >
                <img class="icon-img"
                     alt="<?=__("User Guide")?>"
                     src="<?= $this->getViewFileUrl('Magento_Catalog::images/user-guide.svg')?>">
                <span><?=__("User Guide")?></span>
            </div>
            <span class="column-2-arrow">➜</span>
        </div>

        <div class="container-user-guide" data-role="content">
            <div class="guide-links">
                <a class="links"
                   target="_blank" href="<?=$product->getData('user_guide')?>">
                    <?=__("User Guide")?></a>
                <a class="links"
                   target="_blank" href="<?=$product->getData('install_guide')?>">
                    <?=__("Installation Guide")?></a>
            </div>
        </div>
    </div>


    <div class="container-version" data-role="collapsible">
        <div class="container-row" data-role="trigger">
            <div class="column-1">
                <img class="icon-img"
                    alt="<?=__("Magento Version Soported")?>"
                    src="<?= $this->getViewFileUrl('Magento_Catalog::images/support.svg')?>">
                <span><?=__("Magento Version Soported")?></span>
            </div>
            <span class="column-2-arrow">➜</span>
        </div>

        <div class="container-version-content" data-role="content">
            <div class="container-informacion-version">
                <img class="img-version"
                     alt="<?=__("Magento logo")?>"
                     src="<?= $this->getViewFileUrl('Magento_Catalog::images/magento-icon.png')?>">
                <span class="tex-version"><?=$product->getData('magento_versions')?></span>
            </div>
        </div>
    </div>
</div>
