<div class="container-user-guide">

    <div class="container-items" data-mage-init='{
            "collapsible":{
                "collapsible": true,
                "openedState": "opened",
                "active": false,
                "animate":{ "duration" :300, "easing":"easeOutCubic"}
            }}'>

        <div class="container-row" data-role="title">
            <div class="column-1">
                <img class="icon-img"
                     alt="<?=__("logo Demo")?>"
                     src="<?='https://www.mageplaza.com/assets/images/icons-new/demo.svg'?>">
                <span><?=__("Demo")?></span>
            </div>
            <span class="column-2-arrow">➜</span>

        </div>

        <div class="container-demo-content" data-role="content">
                <div class="container-links">
                    <a class="links links-frontend"><?=__("Frontend")?></a>
                    <a class="links links-backend"><?=__("Backend")?></a>
                </div>
                <div class="container-hosted">
                    <span class="hosted-in|fo"><?=__("This demo is hosted on")?></span>
                    <a class="hosted-links"><?=__("Cloudways")?></a>
                </div>
        </div>

    </div>


    <div class="container-guide-content" data-mage-init='{
            "collapsible":{
                "collapsible": true,
                "openedState": "opened",
                "active": false,
                "animate":{ "duration" :300, "easing":"easeOutCubic"}
            }}'>

        <div class="container-row" data-role="title">
            <div class="column-1">
                <img class="icon-img"
                     alt="<?=__("User Guide")?>"
                     src="<?='https://www.mageplaza.com/assets/images/icons-new/user-guide.svg'?>">
                <span><?=__("User Guide")?></span>
            </div>
            <span class="column-2-arrow">➜</span>
        </div>

        <div class="container-user-guide" data-role="content">
            <div class="guide-links">
                <a class="links"><?=__("User Guide")?></a>
                <a class="links"><?=__("Installation Guide")?></a>
            </div>
        </div>
    </div>


    <div class="container-version" data-mage-init='{
            "collapsible":{
                "collapsible": true,
                "openedState": "opened",
                "active": false,
                "animate":{ "duration" :300, "easing":"easeOutCubic"}
            }}'>
        <div class="container-row" data-role="title">
            <div class="column-1">
                <img class="icon-img"
                    alt="<?=__("Magento Version Soported")?>"
                    src="<?='https://www.mageplaza.com/assets/images/icons-new/support.svg'?>">
                <span><?=__("Magento Version Soported")?></span>
            </div>
            <span class="column-2-arrow">➜</span>
        </div>

        <div class="container-version-content" data-role="content">
            <div class="container-informacion-version">
                <img class="img-version"
                     alt="<?=__("Magento logo")?>"
                     src="<?='https://www.mageplaza.com/assets/img/magento-icon.png'?>">
                <span class="tex-version"><?=__("CE/EE/B2B/Cloud/ Adobe Commerce 2.2.x, 2.3.x, 2.4.x")?></span>
            </div>
        </div>
    </div>
</div>
