<div id="remember-me-box" class="field choice persistent">
    <input type="checkbox" name="persistent_remember_me" class="checkbox" id="remember_mevDaYSI9gaS" checked="checked" title="Remember Me">
    <label for="remember_mevDaYSI9gaS" class="label">
        <span><?= __('Remember Me') ?></span>
    </label>
    <span class="tooltip wrapper">
        <strong class="tooltip toggle"><?= __("What's this?") ?></strong>
        <span class="tooltip content"><?= __('Check "Remember Me" to access your shopping cart on this computer even if you are not signed in.') ?></span>
    </span>
</div>
